### ISSUE TITLE
Add documentation for open source licensing to the Readme

### ISSUE THREAD

**Issue by berlin-ab** [neoremind/fluent-validator#1]
First, I really appreciate your library. I tried it out today and really enjoyed it. 

I had trouble determining whether it was an open-source library that I could use in my project. Would you consider updating the documentation to make it more obvious while visiting the main Github page.

Thanks!

**Comment by neoremind** [comment]
I have added the Apache License 2 for this library. You can see the badge up-above the main page. Now you can use without any license concern. Thanks for taking a look of this little helpful library! If you have any questions, feel free to let me know.
