### ISSUE TITLE
对方法验证的支持如何？

### ISSUE THREAD

**Issue by jayqqaa12** [neoremind/fluent-validator#13]
简单看了一下例子都是使用bean 注解的方式

是否支持 注解类似 spring   MethodValidationPostProcessor 方法验证的方式 ？

**Comment by neoremind** [comment]
您好，我想Spring的注解也是遵循JSR303规范的。所以如果使用了Fluent Validator就不需要用Spring自己的了，详细可以看Spring integration相关的章节。另外使用Fluent Validator可以支持自定义验证注解，与spring bean集成可IoC，这点是比纯Spring或者hibernate方便的地方。
