### ISSUE TITLE
Add custom Error message in on method of Fluent Validator.

### ISSUE THREAD

**Issue by ganeshpanruti** [neoremind/fluent-validator#14]
I have made the changes and having it in my local. Not sure how to push them.

**Comment by neoremind** [comment]
Hi ganeshpanruti,

You can initiate a Pull Request.

Thanks, 
Xu

**Comment by ganeshpanruti** [comment]
Thanks for responding neoremind. Iam new to github, first  i need to proceed with commit right. I thing i dint have permission to proceed. Else can you guide me how to go further to add these changes. I cant create pull request, tell both are of same branch.
