### ISSUE TITLE
A non-successful complex result has a null errors property if the validators have not added errors.

### ISSUE THREAD

**Issue by berlin-ab** [neoremind/fluent-validator#2]
It would be nice if the errors field were always an empty list to avoid the need to null-check for errors before attempting to use them.

We've added an example test to show our expected behavior.
```
    class AlwaysFailingValidator : Validator<String>, ValidatorHandler<String>() {
        override fun validate(context: ValidatorContext?, t: String?): Boolean {
            return false
        }
    }

    it("should always have errors") {
        val result = FluentValidator
                .checkAll()
                .on("some value", AlwaysFailingValidator())
                .failOver()
                .doValidate()
                .result(ResultCollectors.toComplex())

        assertThat(result.isSuccess).isFalse()
        assertThat(result.errors).isNotNull()
    }
```

**Comment by neoremind** [comment]
Hi berlin,

Its really great this little library could facilitate your project. I tried to reproduce, but I believe there should be an empty list of the errors as expected. I was wondering what would be the result of the test case you wrote above, maybe the assertThat(result.errors).isNotNull() ends with FALSE? Below is one test case of mine.

`
        String str = "123";
        ComplexResult ret = FluentValidator.checkAll()
                .on(str, new Validator<String>() {
                    @Override
                    public boolean accept(ValidatorContext context, String s) {
                        return true;
                    }

                    @Override
                    public boolean validate(ValidatorContext context, String s) {
                        return false;
                    }

                    @Override
                    public void onException(Exception e, ValidatorContext context, String s) {

                    }
                })
                .doValidate().result(toComplex());
        System.out.println(ret);
`

Thanks,
Xu

**Comment by berlin-ab** [comment]
The test case above fails on `assertThat(result.errors).isNotNull()`. It should be easy to port from Kotlin to Java.

**Comment by berlin-ab** [comment]
Looks like your ComplexResult2 in your latest snapshot (1.0.6-snapshot) solves this problem. Thanks!
