### ISSUE TITLE
单个参数如何进行校验

### ISSUE THREAD

**Issue by ddacxhs** [neoremind/fluent-validator#21]
您好，我在使用过程中，遇到了方法上单个参数校验问题，这种方式怎样解决了。
尝试过下面这种方式，并不能进行校验
```java
void checkInfo(@FluentValid(HibernateSupportedValidator.class) @NotEmpty(message="info不能为空")String info)
```

**Comment by neoremind** [comment]
你好，使用了@FluentValid(HibernateSupportedValidator.class)这种方式在方法签名上，是需要配合Spring IOC来做拦截的，而参数不能是基本的String类型，一般是自定义的BO/VO/DTO等。
你这种情况，建议不采用Spring IOC方式，直接使用API方式来验证info即可。
