### ISSUE TITLE
com.baidu.unbiz.fluentvalidator.ValidationError#errorCode取值

### ISSUE THREAD

**Issue by ddacxhs** [neoremind/fluent-validator#26]
`fluent-validator`框架支持`Hibernate Validator`，那我该在Hibernate内置注解中如何定义errorCode了，`com.baidu.unbiz.fluentvalidator.ValidationError#errorCode`取值

**Comment by neoremind** [comment]
目前只能使用`HibernateSupportedValidator#setHibernateDefaultErrorCode(int hibernateDefaultErrorCode)`设置一个全局一样的error code。error code是hibernate不支持的，由于Fluent Validator框架封装了hibernate却没有更改它，所以这部分feature暂时无法支持，如果你有好的想法欢迎贡献。
