### ISSUE TITLE
@FluentValid注解未生效是什么原因？

### ISSUE THREAD

**Issue by widy21** [neoremind/fluent-validator#32]
neo
2016/11/22·
一般来说对于前端提交的表单，通常后端会使用SpringMVC或者Struts来处理，一般都会封装成一个XXXForm，这样可以check against这个XXXForm整体即可。在这上面加上@FluentValid注解，然后在各个属性字段上写HibernateValidaion的验证或者自己实现Validator验证都可以，这些都是可以通过注解方式配置的。----大神你好，我现在就是这种方式，只不过我是在springboot项目中，用了@FluentValid注解的方式，但是并没有校验实体类上标注了@NotBlank的字段，这是为什么啊？（测试访问路径：http://localhost:8080/tf）
[SpringBoot-master.zip](https://github.com/neoremind/fluent-validator/files/1855471/SpringBoot-master.zip)

**Comment by neoremind** [comment]
请问问题还存在吗？

**Comment by widy21** [comment]
已经解决了，多谢。
