### ISSUE TITLE
校验错误的信息怎么自定义

### ISSUE THREAD

**Issue by FallenChen** [neoremind/fluent-validator#36]
框架返回的校验错误信息有点不友好，怎么自定义

**Comment by FallenChen** [comment]
![default](https://user-images.githubusercontent.com/24988828/44522354-cfa3de00-a708-11e8-98e1-f5d9626e0422.PNG)  怎么把后面的”错误字段:id“去掉或替换

**Comment by FallenChen** [comment]
问题已解决，是前人自定义，删除就好，抱歉打扰了

**Comment by neoremind** [comment]
解决就好，有问题可以直接邮件我。谢谢。
