### ISSUE TITLE
中文手册网站挂了

### ISSUE THREAD

**Issue by eeokee** [neoremind/fluent-validator#55]
@neoremind  http://neoremind.com/2016/02/java%E7%9A%84%E4%B8%9A%E5%8A%A1%E9%80%BB%E8%BE%91%E9%AA%8C%E8%AF%81%E6%A1%86%E6%9E%B6fluent-validator/  中文手册网站挂了

**Comment by neoremind** [comment]
后台的ecs访问不了，排查中。。。

**Comment by neoremind** [comment]
已恢复
